### ISSUE TITLE
Plateau

### ISSUE THREAD

**Issue by Stormix** [CentraleNantesCS/medev-1#2]
![image](https://user-images.githubusercontent.com/18377687/99640503-41cf0e80-2a49-11eb-8bc5-8205f6fee6d6.png)

**Comment by gabin-s** [comment]
Lien Meet : https://meet.google.com/vcb-cndk-jpg

**Comment by MathieuRH** [comment]
public void initPlateau (){
        listeCases = new ArrayList()<>;
        
        //Première ligne (commence à la case départ)
        listeCases.add(new NonAchetable('case départ'));
        listeCases.add(new Constructible('marron 1', 60));
        listeCases.add(new NonAchetable('communauté'));
        listeCases.add(new Constructible('marron 2', 60));
        listeCases.add(new NonAchetable('taxe 1'));
        listeCases.add(new Gare('Gare 1'));
        listeCases.add(new Constructible('bleu clair 1', 100));
        listeCases.add(new NonAchetable('chance'));
        listeCases.add(new Constructible('bleu clair 2', 100));
        listeCases.add(new Constructible('bleu clair 3', 120));
        
        //Deuxième ligne (commence à la case visite prison)
        listeCases.add(new NonAchetable('visite prison'));
        listeCases.add(new Constructible('violet 1', 140));
        listeCases.add(new NonAchetable('compagnie elec'));
        listeCases.add(new Constructible('violet 2', 140));
        listeCases.add(new Constructible('violet 3', 160));
        listeCases.add(new Gare('Gare 2'));
        listeCases.add(new Constructible('orange 1', 180));
        listeCases.add(new NonAchetable('communauté'));
        listeCases.add(new Constructible('orange 2', 180));
        listeCases.add(new Constructible('orange 3', 200));
        
        //Troisième ligne (commence à la case parc)
        listeCases.add(new NonAchetable('parc gratuit'));
        listeCases.add(new Constructible('rouge 1', 220));
        listeCases.add(new NonAchetable('chance'));
        listeCases.add(new Constructible('rouge 2', 220));
        listeCases.add(new Constructible('rouge 3', 240));
        listeCases.add(new Gare('Gare 3'));
        listeCases.add(new Constructible('jaune 1', 260));
        listeCases.add(new Constructible('jaune 2', 260));
        listeCases.add(new NonAchetable('compagnie eau'));
        listeCases.add(new Constructible('jaune 3', 280));
        
        //Quatrième ligne (commence à la case allez en prison)
        listeCases.add(new NonAchetable('allez en prison'));
        listeCases.add(new Constructible('vert 1', 300));
        listeCases.add(new Constructible('vert 2', 300));
        listeCases.add(new NonAchetable('communauté'));
        listeCases.add(new Constructible('vert 3', 320));
        listeCases.add(new Gare('Gare 4'));
        listeCases.add(new Constructible('chance'));
        listeCases.add(new Constructible('bleu foncé 1', 350));
        listeCases.add(new NonAchetable('taxe 2'));
        listeCases.add(new Constructible('bleu foncé 2', 400));
    }

**Comment by MathieuRH** [comment]
V2

public void initPlateau (){
        listeCases = new ArrayList()<>;
        
        //Première ligne (commence à la case départ)
        listeCases.add(new NonAchetable('case départ'));
        listeCases.add(new Constructible('marron 1', 60));
        listeCases.add(new NonAchetable('communauté'));
        listeCases.add(new Constructible('marron 2', 60));
        listeCases.add(new NonAchetable('taxe 1'));
        listeCases.add(new Gare('Gare 1', 200));
        listeCases.add(new Constructible('bleu clair 1', 100));
        listeCases.add(new NonAchetable('chance'));
        listeCases.add(new Constructible('bleu clair 2', 100));
        listeCases.add(new Constructible('bleu clair 3', 120));
        
        //Deuxième ligne (commence à la case visite prison)
        listeCases.add(new NonAchetable('visite prison'));
        listeCases.add(new Constructible('violet 1', 140));
        listeCases.add(new Company('compagnie elec', 150));
        listeCases.add(new Constructible('violet 2', 140));
        listeCases.add(new Constructible('violet 3', 160));
        listeCases.add(new Gare('Gare 2', 200));
        listeCases.add(new Constructible('orange 1', 180));
        listeCases.add(new NonAchetable('communauté'));
        listeCases.add(new Constructible('orange 2', 180));
        listeCases.add(new Constructible('orange 3', 200));
        
        //Troisième ligne (commence à la case parc)
        listeCases.add(new NonAchetable('parc gratuit'));
        listeCases.add(new Constructible('rouge 1', 220));
        listeCases.add(new NonAchetable('chance'));
        listeCases.add(new Constructible('rouge 2', 220));
        listeCases.add(new Constructible('rouge 3', 240));
        listeCases.add(new Gare('Gare 3', 200));
        listeCases.add(new Constructible('jaune 1', 260));
        listeCases.add(new Constructible('jaune 2', 260));
        listeCases.add(new Company('compagnie eau', 150));
        listeCases.add(new Constructible('jaune 3', 280));
        
        //Quatrième ligne (commence à la case allez en prison)
        listeCases.add(new NonAchetable('allez en prison'));
        listeCases.add(new Constructible('vert 1', 300));
        listeCases.add(new Constructible('vert 2', 300));
        listeCases.add(new NonAchetable('communauté'));
        listeCases.add(new Constructible('vert 3', 320));
        listeCases.add(new Gare('Gare 4', 200));
        listeCases.add(new Constructible('chance'));
        listeCases.add(new Constructible('bleu foncé 1', 350));
        listeCases.add(new NonAchetable('taxe 2'));
        listeCases.add(new Constructible('bleu foncé 2', 400));
    }

**Comment by MathieuRH** [comment]
/*
    * Fonction de suppression des joueurs fauchés
    */
    public void elimineJoueurs() {
        int indice = 0;
        while (indice <= listeJoueurs.size()) {
            Joueur joueur = listeJoueurs.get(indice);
            if (joueur.getMoney() <= 0) {
                listeJoueurs.get(indice) = null;
                System.out.println('le joueur n°' + Integer.toString(indice) + 'a perdu');
                indice -= 1;
            }
            indice += 1;
        }
    }
    
    /*
    * Tour de jeu du plateau (boucle principale)
    */
    public void tourDeJeu () {
        while (listeJoueurs.size()>1){
            for (Joueur j:listeJoueurs){
                j.monTourDeJeu();
            }
            elimineJoueurs();
        }
    }

**Comment by adrientiburce** [comment]
/**
     * affiche case 0 à 9 inclus en bas du plateau
     */
    public void afficheBas() {
        System.out.print("|");
        for (int i = 10; i >= 0; i--) {
            listeCases.get(i).affiche();
            System.out.print("|");
        }
        System.out.println();
    }

    /**
     * affiche case 20 à 30 inclus en haut du plateau
     */
    public void afficheTop() {
        System.out.print("|");
        for (int i = 20; i <= 30; i++) {
            listeCases.get(i).affiche();
            System.out.print("|");
        }
        System.out.println();
    }

    public void affiche() {
        afficheTop();
        // 19 & 29
        int leftCase = 19;
        int rightCase = 29;

        for (int i = 0; i < 9; i++) {
            System.out.print("|");
            listeCases.get(leftCase).affiche();

            // 9 case vides du milieu
            for (int j = 0; j < 9; j++) {
                System.out.print("|");
                System.out.print(fixedLengthString("", 20));
            }
            System.out.print("|");
            listeCases.get(rightCase).affiche();
            System.out.println("|");

            leftCase--;
            rightCase++;
        }

        afficheBas();
    }

    public String fixedLengthString(String string, int length) {
        return String.format("%1$" + length + "s", string);
    }

**Comment by adrientiburce** [comment]
public void affiche() {
        String s = this.toString();
        if (s.length() > 20) {
            s = s.substring(0, 20);
            System.out.print(s);
        } else {
            System.out.print(fixedLengthString(this.toString(), 20));
        }
    }

    public String fixedLengthString(String string, int length) {
        return String.format("%1$" + length + "s", string);
    }
